= 机酒产品接口文档指南
机酒开发组成员;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-request-fields-title: 请求参数说明
:operation-curl-request-title: curl请求样例
:operation-http-request-title: http请求样例
:operation-http-response-title: http响应
:operation-response-body-title: 响应体

[[概述]]
= 概述

机酒产品接口文档

[[状态码描述]]
= 状态码描述

[[接口描述]]
= 接口描述

[[机票推荐接口]]
== 机票推荐接口

推荐默认机票,当前逻辑如下：

1. 先根据出发地，目的地以及出发时间和返程时间查询机票列表

2. 根据过滤条件过滤满足条件的机票

3. 最终根据排序规则给机票选择计算相应的评分，然后根据评分倒序排序，最终选择第一条机票作为推荐机票

operation::flight-recommend[snippets='request-fields,curl-request,http-request,http-response']

[[机票列表接口]]
== 机票列表接口

获取实时机票列表接口。

operation::flight-list[snippets='request-fields,curl-request,http-request,http-response']

[[机票信息查询接口]]
== 机票信息查询接口

根据key查询机票信息，目前仅支持往返机票查询。

如果goKey==backKey说明是套餐机票，如果不等则说明是自由组合机票。

operation::flight-info[snippets='request-fields,curl-request,http-request,http-response']


== 酒店列表接口

根据规则筛选规则展示酒店列表

operation::hotel-list[snippets='request-fields,curl-request,http-request,http-response']

== 酒店详情接口

酒店详情获取接口，默认房型第一条数据为选中数据

operation::hotel-info[snippets='request-fields,curl-request,http-request,http-response']

== 动态酒店推荐接口

动态酒店推荐接口，酒店获取逻辑为默认列表排序前Top5 的酒店，如果都不存在报价则推荐失败。

operation::recommend-hotel[snippets='request-fields,curl-request,http-request,http-response']
