spring:
  redis:
    cluster:
      nodes: xxxxxxx:6379,xxxxxxx:6379
      max-redirects: 5
      password: schrd
      timeout: 5

caching:
  types:
    - CAFFEINE
  config:
    caffeine:
      spec: maximumSize=100,expireAfterWrite=1h,recordStats
  configs:
    hblist:
      caffeine:
        spec: maximumSize=5000,expireAfterAccess=30m,recordStats
      redis:
        timeToLive: 30m
    flist:
      caffeine:
        spec: maximumSize=5000,expireAfterAccess=15m,refreshAfterWrite=10m,recordStats
        cacheNullValues: false
      redis:
        timeToLive: 15m
        cacheNullValues: false

datasources:
  dm-master:
    driverClassName: org.postgresql.Driver
    jdbcUrl: 'jdbc:postgresql://150.242.184.16:7654/cornel_product'
    username: postgres
    password: 123456
    maximumPoolSize: 5
    idleTimeout: 600000
    maxLifetime: 1800000

