debug: true

spring:
  redis:
    cluster:
      nodes: xxxxxxx:6379,xxxxxxx:6379
      max-redirects: 5
      password: schrd
      timeout: 5

jetcache:
  statIntervalMinutes: 1
  areaInCacheName: false
  local:
    default:
      type: caffeine
      limit: 100
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      expireAfterWriteInMillis: 60000
# remote 需要适配下公司sedis或者redis集群
#  remote:
#    default:
#      type: redis.lettuce
#      keyConvertor: fastjson
#      valueEncoder: java
#      valueDecoder: java
#      uri:
#        - redis://l-schrd2.vc.beta.cn0:6379
#        - redis://l-schrd2.vc.beta.cn0:7379
#      password:
#        - schrd

caching:
  types:
    - CAFFEINE
  config:
    caffeine:
      spec: maximumSize=100,expireAfterWrite=1h,recordStats
  configs:
    hblist:
      caffeine:
        spec: maximumSize=5000,expireAfterAccess=10s,recordStats
    flist:
      caffeine:
        spec: maximumSize=5000,expireAfterAccess=15m,refreshAfterWrite=10m,recordStats
      redis:
        timeToLive: 15m

we-chat:
   code2session: https://api.weixin.qq.com/sns/jscode2session?appid=%s&secret=%s&js_code=%s&grant_type=authorization_code

        
datasources:
  dm-master:
    driverClassName: org.postgresql.Driver
    jdbcUrl: 'jdbc:postgresql://150.242.184.16:7654/cornel_product'
    username: postgres
    password: 123456
    maximumPoolSize: 5
    idleTimeout: 600000
    maxLifetime: 1800000
