debug: true
sedis:
  namespace: si_lvtu_lm
  cipher: be1e8df1
  zk-address: zk1.dba.beta.qunar.com:2181,zk2.dba.beta.qunar.com:2181,zk3.dba.beta.qunar.com:2181,zk4.dba.beta.qunar.com:2181,zk5.dba.beta.qunar.com:2181


spring:
  redis:
    cluster:
      nodes: 10.90.185.253:6379,10.90.185.226:6379
      max-redirects: 5
      password: schrd
      timeout: 5

jetcache:
  statIntervalMinutes: 1
  areaInCacheName: false
  local:
    default:
      type: caffeine
      limit: 100
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      expireAfterWriteInMillis: 60000
# remote 需要适配下公司sedis或者redis集群
#  remote:
#    default:
#      type: redis.lettuce
#      keyConvertor: fastjson
#      valueEncoder: java
#      valueDecoder: java
#      uri:
#        - redis://l-schrd2.vc.beta.cn0:6379
#        - redis://l-schrd2.vc.beta.cn0:7379
#      password:
#        - schrd

caching:
  types:
    - CAFFEINE
  config:
    caffeine:
      spec: maximumSize=100,expireAfterWrite=1h,recordStats
  configs:
    hblist:
      caffeine:
        spec: maximumSize=5000,expireAfterAccess=10s,recordStats
    flist:
      caffeine:
        spec: maximumSize=5000,expireAfterAccess=15m,refreshAfterWrite=10m,recordStats
      redis:
        timeToLive: 15m

        
datasources:
  fhtts-master:
    driverClassName: org.postgresql.Driver
    jdbcUrl: 'jdbc:postgresql://xxxxxx:5432/fh_tts_beta'
    username: xxxxx
    password: xxxxx
    maximumPoolSize: 5
    idleTimeout: 600000
    maxLifetime: 1800000
