
caching:
  types:
    - CAFFEINE
  config:
    caffeine:
      spec: maximumSize=100,expireAfterWrite=1h,recordStats
  configs:
    hblist:
      caffeine:
        spec: maximumSize=5000,expireAfterAccess=30m,recordStats
      redis:
        timeToLive: 30m
    flist:
      caffeine:
        spec: maximumSize=5000,expireAfterAccess=15m,refreshAfterWrite=10m,recordStats
        cacheNullValues: false
      redis:
        timeToLive: 15m
        cacheNullValues: false

datasources:
  fhtts-master:
    driverClassName: org.postgresql.Driver
    jdbcUrl: 'jdbc:postgresql://xxxxxx:5432/fh_tts_beta'
    username: xxxxx
    password: xxxxx
    maximumPoolSize: 5
    idleTimeout: 600000
    maxLifetime: 1800000

