debug: true

spring:
  redis:
    cluster:
      nodes: xxxxxxx:6379,xxxxxxx:6379
      max-redirects: 5
      password: schrd
      timeout: 5

caching:
  types:
    - CAFFEINE
  config:
    caffeine:
      spec: maximumSize=100,expireAfterWrite=1h,recordStats
  configs:
    hblist:
      caffeine:
        spec: maximumSize=5000,expireAfterAccess=30m,recordStats
    flist:
      caffeine:
        spec: maximumSize=5000,expireAfterAccess=15m,refreshAfterWrite=10m,recordStats
      redis:
        timeToLive: 15m
#    make-price-info:
#      caffeine:
#        spec: maximumSize=5000,expireAfterAccess=30m,recordStats
#    check-abroad-cache:
#      caffeine:
#        spec: maximumSize=5000,expireAfterAccess=30m,recordStats
    fh-py-flight-list:
      caffeine:
        spec: maximumSize=5000,expireAfterWrite=5m,recordStats
    hotel-comment-tag:
      caffeine:
        spec: maximumSize=10000,expireAfterWrite=6h,recordStats
    fh-py-res-config:
      caffeine:
        spec: maximumSize=10000,expireAfterWrite=30m,recordStats
    fh-online-hotel:
      caffeine:
        spec: maximumSize=10000,expireAfterWrite=5m,recordStats
    fh-hotel-simple-base-info:
      caffeine:
        spec: maximumSize=100000,expireAfterWrite=30m,recordStats    
        cacheNullValues: false
we-chat:
  code2session: https://api.weixin.qq.com/sns/jscode2session?appid=%s&secret=%s&js_code=%s&grant_type=authorization_code
  appId: xxxxx
  appSecret: xxxx

ali-config:
  accessKeyId: LTAI4FrsE2fex1MYUNFFYBKG
  accessSecret: hfkMjTSyoZhGqksvk3fq4QUNw0zOqo
  loginValidcodeId: SMS_176539582


datasources:
  dm-master:
    driverClassName: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://150.242.184.16:7654/cornel_product
    username: postgres
    password: cornel*..123
    maximumPoolSize: 5
    idleTimeout: 600000
    maxLifetime: 1800000

