debug: true
sedis:
  namespace: si_lvtu_lm
  cipher: be1e8df1
  zk-address: zk1.dba.beta.qunar.com:2181,zk2.dba.beta.qunar.com:2181,zk3.dba.beta.qunar.com:2181,zk4.dba.beta.qunar.com:2181,zk5.dba.beta.qunar.com:2181


spring:
  redis:
    cluster:
      nodes: 10.90.185.253:6379,10.90.185.226:6379
      max-redirects: 5
      password: schrd
      timeout: 5

caching:
  types:
    - CAFFEINE
  config:
    caffeine:
      spec: maximumSize=100,expireAfterWrite=1h,recordStats
  configs:
    hblist:
      caffeine:
        spec: maximumSize=5000,expireAfterAccess=30m,recordStats
    flist:
      caffeine:
        spec: maximumSize=5000,expireAfterAccess=15m,refreshAfterWrite=10m,recordStats
      redis:
        timeToLive: 15m
#    make-price-info:
#      caffeine:
#        spec: maximumSize=5000,expireAfterAccess=30m,recordStats
#    check-abroad-cache:
#      caffeine:
#        spec: maximumSize=5000,expireAfterAccess=30m,recordStats
    fh-py-flight-list:
      caffeine:
        spec: maximumSize=5000,expireAfterWrite=5m,recordStats
    hotel-comment-tag:
      caffeine:
        spec: maximumSize=10000,expireAfterWrite=6h,recordStats
    fh-py-res-config:
      caffeine:
        spec: maximumSize=10000,expireAfterWrite=30m,recordStats
    fh-online-hotel:
      caffeine:
        spec: maximumSize=10000,expireAfterWrite=5m,recordStats
    fh-hotel-simple-base-info:
      caffeine:
        spec: maximumSize=100000,expireAfterWrite=30m,recordStats    
        cacheNullValues: false
        
datasources:
  fhtts-master:
    driverClassName: org.postgresql.Driver
    jdbcUrl: 'jdbc:postgresql://xxxxxx/fh_tts_beta'
    username: xxxxx
    password: xxxxx
    maximumPoolSize: 5
    idleTimeout: 600000
    maxLifetime: 1800000
